---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webctrlAgent.name }}
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.webctrlAgent.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.webctrlAgent.name }}
    spec:
      containers:
        - image: {{ .Values.webctrlAgent.image }}
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /app/config.yaml
              name: vol-config
              subPath: config.yaml
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      restartPolicy: Always
      securityContext: {}
      volumes:
        - name: vol-config
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ .Values.webctrlAgent.webCTRLAgentConfigYamlSecretName }}
