---
{{- if eq .Release.Namespace "dcv" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cron-examsync-configmap
data:
  url: {{ if eq .Release.Namespace "dcv" }}{{ printf "https://%s/sync.php" .Values.hostname }}{{ else }}{{ printf "https://dcvtool-%s.rit.edu/sync.php" .Release.Namespace }}{{ end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-exam-sync
spec:
  schedule: "* */6 * * *" # Run every 4 hrs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-exam-sync
              image: buildpack-deps:curl
              imagePullPolicy: IfNotPresent
              command: [ "/bin/sh" ]
              args: [ "-c", "curl -X POST -d 'token=$(TOKEN)' $(URL)" ]
              env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: dcv-dataconn-sec
                    key: SISEXAMSYNC
              - name: URL
                valueFrom:
                  configMapKeyRef:
                    name: cron-examsync-configmap
                    key: url
          restartPolicy: OnFailure
{{- end -}}
